### ISSUE TITLE
Ubuntu 20.04 Architecture description on Raspberry PI

### ISSUE THREAD

**Issue by jfmatth** [rancher/k3s-ansible#31]
Has anyone seen this Raspberry Pi 3 with Ubuntu 20.04, the Architecture isn't named "arm", but rather "aarch64"

Consequently, nothing works with a rename of the architecture name

**Comment by paulfantom** [comment]
Previously I did a major refactor which included support for `aarch64` in https://github.com/rancher/k3s/pull/1649. Sadly I don't have time right now to do this refactor again in this repo.

**Comment by fnord123** [comment]
I believe https://github.com/rancher/k3s-ansible/pull/34 should fix this if I am understanding it correctly.  I was able to install on a RPi4 running Ubuntu 20.04 64 bit using it.

**Comment by fnord123** [comment]
@jfmatth a fix has been merged, can you take a look and see if it addresses the issue, then mark it closed if so? Thanks! :)

**Comment by jfmatth** [comment]
@fnord123 Thanks for the update, I'll try to take a look this weekend, and if all looks good, ill close.

thanks so much

**Comment by anthr76** [comment]
Just ran this playbook on my 20.04 Raspberry Pi 4s on 64 bit and can confirm all went well :)

```
k3s-master-01   Ready    master   84s   v1.19.2+k3s1
k3s-worker-01   Ready    <none>   48s   v1.19.2+k3s1
k3s-worker-02   Ready    <none>   48s   v1.19.2+k3s1
k3s-worker-03   Ready    <none>   48s   v1.19.2+k3s1
```
