### ISSUE TITLE
Activate cgroup support failed

### ISSUE THREAD

**Issue by Vexet83** [rancher/k3s-ansible#40]
When running the playbook after following the Readme and changing the user I get the following error when running the playbook.

TASK [raspbian : Activating cgroup support] **************************************************************************************************************************************************************************************************************************************************************************************************************************************************** 
fatal: [192.168.50.51]: FAILED! => {"msg": "The conditional check 'raspbian is true' failed. The error was: template error while templating string: no test named 'true'. String: {% if raspbian is true %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/brett/k3s-ansible/roles/raspbian/tasks/main.yml': line 10, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Activating cgroup support\n  ^ here\n"}
fatal: [192.168.50.215]: FAILED! => {"msg": "The conditional check 'raspbian is true' failed. The error was: template error while templating string: no test named 'true'. String: {% if raspbian is true %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/brett/k3s-ansible/roles/raspbian/tasks/main.yml': line 10, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Activating cgroup support\n  ^ here\n"}
fatal: [192.168.50.196]: FAILED! => {"msg": "The conditional check 'raspbian is true' failed. The error was: template error while templating string: no test named 'true'. String: {% if raspbian is true %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/brett/k3s-ansible/roles/raspbian/tasks/main.yml': line 10, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Activating cgroup support\n  ^ here\n"}
fatal: [192.168.50.204]: FAILED! => {"msg": "The conditional check 'raspbian is true' failed. The error was: template error while templating string: no test named 'true'. String: {% if raspbian is true %} True {% else %} False {% endif %}\n\nThe error appears to be in '/home/brett/k3s-ansible/roles/raspbian/tasks/main.yml': line 10, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Activating cgroup support\n  ^ here\n"}

After that fails the playbook ends. I'm trying to deploy it to 4 Pi4s running HypriotOS. I am new to all this so trying to learn.

**Comment by fnord123** [comment]
Can you include the output of 'ansible --version'? With that I can try to
repro.

**Comment by Vexet83** [comment]
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]

**Comment by Vexet83** [comment]
I'm running Ubuntu 18.04 VM on vmware with all the stuff like ansible, kubectl, and such to do all this on. I deployed in the past once to a cluster of 3 but something broke I think and I wasn't able to adjust the cluster after. Couldn't add a node nor could I run the reset yml. I had to re-flash the sd-cards. and ive tried using different ways to run everything to include Ubuntu 20.04 VM, a different 18.04 VM, 18.04 & 20.04 subsystem for windows. I got the same error on each. Do you think it is a hardware issue?

**Comment by fnord123** [comment]
I'm running ansible on 20.04 on WSL and am busily setting up some VMs with
various OS for target machines to install on, will see what I can do to
repro.  Seems unlikely to be a hardware issue.  What version of HypriotOS
are you running on the RPis?  I'll try that on my test RPi as well.

**Comment by Vexet83** [comment]
Version 1.12.1. I will add I got the same error running Rasbian both before and after the change that came with the 8Gb boards. But as of now I want to run Hypriot so that's what I need to have working.

**Comment by klutchell** [comment]
+1 for me. I'm running Ubuntu aarch64 on my remote devices.

```bash
ansible 2.9.6
  config file = /home/kharding/workspace/k3s-ansible/ansible.cfg
  configured module search path = ['/home/kharding/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
```

**Comment by cphang99** [comment]
I'm also seeing this on ubuntu 20.04

```
TASK [ubuntu : Enable cgroup via boot commandline if not already enabled] *****************************************************************************************************************************************
Saturday 06 June 2020  13:45:15 +0100 (0:00:00.032)       0:00:18.442 ********* 
fatal: [188.166.136.95]: FAILED! => {"changed": false, "msg": "Destination /boot/firmware/cmdline.txt does not exist !", "rc": 257}
```

**Comment by fnord123** [comment]
I have reproduced the issue using a virtual Ubuntu 20.04 ansible host and a pair of Ubuntu 20.04 raspberry pis.  Debugging now.

**Comment by fnord123** [comment]
I can't repro it when using my WSL-hosted Debian Ansible host using the same target Ubuntu 20.04 RPi listed above. I've reproed it using WSL-host Ubuntu 20.04 Ansible host.  Debian is using Python 2.7.16, Ubuntu is using Python 3.8.2.  So likely that's why I didn't see it when I test - I always tested using my Debian Ansible host.    So this is an Ansible host problem, not a target device problem.  Debugging further.

**Comment by fnord123** [comment]
Ok folks, I have a PR in that should fix this. Sorry about the bug, I introduced it by only testing on my Debian ansible host.  The PR fixes it for Ubuntu 20.04 Ansible hosts.

**Comment by Vexet83** [comment]
So if I make the changes to the roles/rasbian/tasks/main.yml in the Fix Rasbian role ref it should work?

**Comment by Vexet83** [comment]
Gave it a shot with the changes on Ubuntu 18.04 with Ansible 2.9.9 host and it was successful. We shall see if I end up get a different error later whenever I try to add a node in the future and need to rerun the playbook to add it. Thank you very much for your assistance fnord123!!

**Comment by jfmatth** [comment]
So put the PR into my code by hand and it fixed the error associated with this issue, but now I'm getting errors that it wants to update the cmdline on  firmware, see below.  I'm running 3 simple 20.04 VM's on my laptop, don't think this is necessary

```
TASK [ubuntu : Enable cgroup via boot commandline if not already enabled] *************************************************************************************************************
Wednesday 17 June 2020  11:48:44 -0700 (0:00:00.049)       0:00:18.147 ********
fatal: [node-1.mshome.net]: FAILED! => {"changed": false, "msg": "Destination /boot/firmware/cmdline.txt does not exist !", "rc": 257}
fatal: [master.mshome.net]: FAILED! => {"changed": false, "msg": "Destination /boot/firmware/cmdline.txt does not exist !", "rc": 257}
fatal: [node-2.mshome.net]: FAILED! => {"changed": false, "msg": "Destination /boot/firmware/cmdline.txt does not exist !", "rc": 257}
```

I commented out the code from the ubuntu task main.yml and the issue went away, just not sure why we are enabling cgroup on a stock 20.04 image?

here is my new main.yml, sorry for no PR

```
---
# - name: Enable cgroup via boot commandline if not already enabled
#   lineinfile:
#     path: /boot/firmware/cmdline.txt
#     backrefs: yes
#     regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
#     line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
#   when:
#     - ansible_distribution == 'Ubuntu'

- name: Reboot to enable cgroups
  reboot:
  when:
    - ansible_distribution == 'Ubuntu'
```
