### ISSUE TITLE
Add fail2ban and unattended-upgrade for Ubuntu

### ISSUE THREAD

**Issue by mysticaltech** [rancher/k3s-ansible#55]
Hello, wouldn't it be nice to do basic hardening to the ubuntu nodes (and others also) ? Like installing fail2ban and making sure unattended-upgrades are activate for security patches? @geerlingguy I know you have tons of playbooks for this, what do you think?

**Comment by itwars** [comment]
Hi, my optinion: it's out of scope, these playbooks are of build and maintain k3s cluster. I don't say hardening is not necessary but it can and have to be done with other playbooks.

**Comment by geerlingguy** [comment]
Agreed; I was going to mention that this playbook benefits from the simple focus of setting up K3s and nothing else. It is a good playbook that can be integrated into another one that does any hardening and also deploys your applications into the cluster.

**Comment by mysticaltech** [comment]
Ok I understand, thanks!
