### ISSUE TITLE
"{{ items }}" in /prereq/tasks/main.yml should be "{{ item }}"?

### ISSUE THREAD

**Issue by guofengzh** [rancher/k3s-ansible#56]
"{{ items }}" in [this line](https://github.com/rancher/k3s-ansible/blob/master/roles/prereq/tasks/main.yml#L35) should be "{{ item }}".

Ansible version: 2.9.10
OS: CentOS Linux release 7.8.2003 (Core)

After changed to {{ item }}, the task finished successfully.

**Comment by evrardjp** [comment]
You're right. Did you propose a PR?

**Comment by guofengzh** [comment]
PR? how could I do it?

**Comment by evrardjp** [comment]
You could fork this repository (it's one click on the main repo page) to your own repository, change the line in your repository and commit it (either using github's web interface or using your favorite git client), and then there will be a link on your forked repository's github page to "Create a pull request" in this repository. Click on it, and it will automatically propose the change for the reviewers of this project.

Aditional tip: when writing the commit message, you can type: "Fixes: #56" and merging your PR will auto-close this issue!
