### ISSUE TITLE
Activating cgroups raise error on Ubuntu 20.04

### ISSUE THREAD

**Issue by dtourde** [rancher/k3s-ansible#60]
On Ubuntu Server 20.04 file `/boot/firmware/cmdline.txt` don't exists on a fresh install.

It causes fail on the task `- name: Enable cgroup via boot commandline if not already enabled`

**Comment by dtourde** [comment]
#59 fix the problem with creation of the file

**Comment by fnord123** [comment]
This issue is a duplicate of #40 and #44 .  Pull request #54 fixes it.

**Comment by dtourde** [comment]
> This issue is a duplicate of #40 and #44 . Pull request #54 fixes it.

As #60 is a duplicate, I close it.

**Comment by jdmarshall** [comment]
But I'm running k3s-ansible latest release and still having this problem?

Also it looks like on Armbian they moved the file for some reason.  Still trying to figure out if the format is even the same...

**Comment by dtourde** [comment]
> This is listed as fixed 18 days ago, but it looks like the PR didn't land until 2 days ago, so presumably not in a release at present? Am I reading that right?
> 
> (I always found it odd how GitHub wants you to close an issue when it hasn't been fixed in the wild yet)

PR #54 is merged and should fix it.
I didn't had time to test it yet, though.
